{% set name = "google-cloud-aiplatform" %}
{% set version = "1.30.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-aiplatform-{{ version }}.tar.gz
  sha256: 7552a6b2e66d7a9ff3c4b2bb95b0e9c182e7475dfb35d6347e9299f78779135a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - packaging >=14.3
    - google-cloud-storage >=1.32.0,<3.0.0dev
    - google-cloud-bigquery-core >=1.15.0,<4.0.0dev
    - google-cloud-resource-manager >=1.3.3,<3.0.0dev
    - shapely <2.0.0

test:
  imports:
    - google
    - vertexai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-aiplatform
  summary: Vertex AI API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
